# Generated by Django 3.1.2 on 2021-03-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_tags',
            name='articleID',
        ),
        migrations.RemoveField(
            model_name='article_tags',
            name='tagID',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='articleID',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='user_views',
            name='articleID',
        ),
        migrations.RemoveField(
            model_name='user_views',
            name='userID',
        ),
        migrations.DeleteModel(
            name='Article_Categorys',
        ),
        migrations.DeleteModel(
            name='Article_Tags',
        ),
        migrations.DeleteModel(
            name='Categorys',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='User_Views',
        ),
    ]
