# Generated by Django 3.1.2 on 2021-03-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20210311_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
    ]
