# Generated by Django 3.1.2 on 2021-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20210311_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='created_on',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='click_counter',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='hot_score',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='slug',
        ),
        migrations.AddField(
            model_name='articles',
            name='sapo',
            field=models.TextField(default='sapo'),
            preserve_default=False,
        ),
    ]
