# Generated by Django 3.1.2 on 2021-03-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_remove_articles_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagID', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.TextField()),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
