# Generated by Django 3.1.2 on 2021-03-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_remove_user_comments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comments',
            name='time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
