# Generated by Django 3.1.2 on 2021-03-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_user_comments_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
