# Generated by Django 3.1.2 on 2021-03-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('articleID', models.IntegerField(primary_key=True, serialize=False)),
                ('representation', models.TextField()),
                ('link', models.TextField()),
                ('category', models.TextField()),
                ('displayContent', models.TextField()),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('tags', models.TextField()),
                ('sapo', models.TextField()),
            ],
        ),
    ]
