# Generated by Django 3.1.2 on 2021-03-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_articles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='articles',
            table='articles',
        ),
    ]
