# Generated by Django 3.1.2 on 2021-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_auto_20210312_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleID', models.IntegerField()),
                ('tagID', models.IntegerField()),
            ],
            options={
                'db_table': 'article_tags',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
