# Generated by Django 3.1.2 on 2021-03-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_auto_20210312_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleID', models.IntegerField()),
                ('categoryID', models.IntegerField()),
            ],
            options={
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('representation', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
