# Generated by Django 3.1.2 on 2021-03-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_article_category_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('articleID', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'user_view',
            },
        ),
    ]
