# Generated by Django 3.1.2 on 2021-03-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0018_user_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_tags',
            name='articleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.articles'),
        ),
        migrations.AlterField(
            model_name='article_tags',
            name='tagID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.tags'),
        ),
        migrations.AlterUniqueTogether(
            name='article_tags',
            unique_together={('articleID', 'tagID')},
        ),
        migrations.AlterModelTable(
            name='article_tags',
            table=None,
        ),
    ]
