# Generated by Django 3.1.2 on 2021-03-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_auto_20210314_0007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article_tags',
            table='article_tags',
        ),
    ]
