# Generated by Django 3.1.2 on 2021-03-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0020_auto_20210314_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_tags',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
