# Generated by Django 3.1.2 on 2021-03-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0022_auto_20210314_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_comments',
            name='userID',
        ),
    ]
