# Generated by Django 3.1.2 on 2021-03-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0023_remove_user_comments_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_comments',
            name='articleID',
        ),
    ]
