# Generated by Django 3.1.2 on 2021-03-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0025_auto_20210316_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_comments',
            name='articleID',
        ),
        migrations.RemoveField(
            model_name='user_comments',
            name='userID',
        ),
    ]
