# Generated by Django 3.1.2 on 2021-03-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0027_auto_20210316_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_comments',
            name='userID',
        ),
    ]
