# Generated by Django 3.1.2 on 2021-03-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0029_auto_20210317_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_comments',
            name='articleID',
        ),
    ]
