# Generated by Django 3.1.2 on 2021-03-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0030_remove_user_comments_articleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_comments',
            name='articleID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.articles'),
            preserve_default=False,
        ),
    ]
