# Generated by Django 3.1.2 on 2021-03-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0032_auto_20210317_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_comments',
            name='articleID',
            field=models.IntegerField(),
        ),
    ]
