# Generated by Django 3.1.2 on 2021-03-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0037_auto_20210318_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='weight_score',
            new_name='click_counter',
        ),
        migrations.AddField(
            model_name='articles',
            name='hot_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
