# Generated by Django 3.1.7 on 2021-03-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0039_user_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_category',
            old_name='countj',
            new_name='count',
        ),
    ]
